version: '3'

services:
  myapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - myapp-network

  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - myapp-network

networks:
  myapp-network:
    
